// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk3FJpaG3B5PUKOMgqi0lUtNxEONNfzt0',
    appId: '1:121066331295:web:4e6b77b8af0410d51296aa',
    messagingSenderId: '121066331295',
    projectId: 'chatapp-e689f',
    authDomain: 'chatapp-e689f.firebaseapp.com',
    storageBucket: 'chatapp-e689f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBter17jF4-IMKRJ0Y4H9TQjHAs2XQO9Ac',
    appId: '1:121066331295:android:a88898e1064f253e1296aa',
    messagingSenderId: '121066331295',
    projectId: 'chatapp-e689f',
    storageBucket: 'chatapp-e689f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4QAqqxqG0TaH6IX_zh8bezEG0NKkFgEI',
    appId: '1:121066331295:ios:a971c2189a06b4971296aa',
    messagingSenderId: '121066331295',
    projectId: 'chatapp-e689f',
    storageBucket: 'chatapp-e689f.appspot.com',
    iosBundleId: 'com.example.hiddenmenu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4QAqqxqG0TaH6IX_zh8bezEG0NKkFgEI',
    appId: '1:121066331295:ios:3037b4f48e8a86651296aa',
    messagingSenderId: '121066331295',
    projectId: 'chatapp-e689f',
    storageBucket: 'chatapp-e689f.appspot.com',
    iosBundleId: 'com.example.hiddenmenu.RunnerTests',
  );
}
